fx_version 'cerulean'
game 'gta5'
lua54 'yes'

shared_scripts {
    'shared/enums.lua',
    'shared/errors.lua',
    'shared/constants.lua',
    'shared/schemas.lua',
    'shared/validators.lua',
    'shared/types/framework.lua',
    'config/providers.lua',
    'config/features.lua',
    'config/services.lua',
    'config/pricing.lua',
    'config/cancellation.lua',
    'config/config.lua'
}

server_scripts {
    'server/core/result.lua',
    'server/core/clock.lua',
    'server/core/logger.lua',
    'server/core/event_bus.lua',
    'server/adapters/framework/interface.lua',
    'server/adapters/framework/qbcore.lua',
    'server/adapters/framework/qbox.lua',
    'server/adapters/framework/esx.lua',
    'server/adapters/framework/standalone.lua',
    'server/adapters/money/interface.lua',
    'server/adapters/money/qbcore.lua',
    'server/adapters/money/qbox.lua',
    'server/adapters/money/esx.lua',
    'server/adapters/money/standalone.lua',
    'server/adapters/optional_base.lua',
    'server/adapters/phone/interface.lua',
    'server/adapters/housing/interface.lua',
    'server/adapters/motel/interface.lua',
    'server/adapters/dispatch/interface.lua',
    'server/adapters/appearance/interface.lua',
    'server/adapters/evidence/interface.lua',
    'server/adapters/provider_resolver.lua',
    'server/adapters/database/interface.lua',
    'server/adapters/database/oxmysql.lua',
    'server/core/migrations.lua',
    'server/repositories/base_repository.lua',
    'server/services/identity_service.lua',
    'server/domain/worker_profile.lua',
    'server/repositories/worker_profile_repository.lua',
    'server/services/worker_profile_service.lua',
    'server/domain/client_profile.lua',
    'server/repositories/client_profile_repository.lua',
    'server/services/client_profile_service.lua',
    'config/permissions.lua',
    'server/services/permission_service.lua',
    'server/domain/booking.lua',
    'server/repositories/booking_repository.lua',
    'server/state/booking_state_machine.lua',
    'server/repositories/booking_event_repository.lua',
    'server/core/reservations.lua',
    'server/services/booking_timeline_service.lua',
    'server/services/booking_reservation_service.lua',
    'server/domain/price_quote.lua',
    'server/services/service_catalog.lua',
    'server/services/pricing_service.lua',
    'server/services/booking_service.lua',
    'server/domain/deposit.lua',
    'server/repositories/deposit_repository.lua',
    'server/services/deposit_service.lua',
    'server/repositories/payment_repository.lua',
    'server/services/settlement_service.lua',
    'server/services/refund_service.lua',
    'server/bootstrap.lua'
}
client_scripts {
    'client/bootstrap.lua',
    'client/adapters/target/interface.lua',
    'client/adapters/notify/interface.lua'
}
