NightShift = NightShift or {}

NightShift.Errors = NightShift.Errors or {}

NightShift.Errors.Codes = NightShift.Errors.Codes or {
    INVALID_CONFIG = 'INVALID_CONFIG',
    UNKNOWN_PROVIDER = 'UNKNOWN_PROVIDER',
    PROVIDER_UNAVAILABLE = 'PROVIDER_UNAVAILABLE',
    DUPLICATE_ID = 'DUPLICATE_ID',
    INVALID_PRICE = 'INVALID_PRICE',
    INVALID_DURATION = 'INVALID_DURATION',
    INVALID_LOCATION_REFERENCE = 'INVALID_LOCATION_REFERENCE',
    INVALID_EVENT = 'INVALID_EVENT',
    HANDLER_FAILED = 'HANDLER_FAILED',
    DB_INVALID_ARGUMENT = 'DB_INVALID_ARGUMENT',
    DB_UNAVAILABLE = 'DB_UNAVAILABLE',
    DB_QUERY_FAILED = 'DB_QUERY_FAILED',
    DB_TRANSACTION_FAILED = 'DB_TRANSACTION_FAILED',
    DB_HEALTHCHECK_FAILED = 'DB_HEALTHCHECK_FAILED',
    VALIDATION = 'VALIDATION_FAILED',
    UNAVAILABLE_CAPABILITY = 'CAPABILITY_UNAVAILABLE',
    BOOTSTRAP_STAGE = 'BOOTSTRAP_STAGE_FAILED',
    CLEANUP_FAILED = 'CLEANUP_FAILED',
    INTERNAL = 'INTERNAL_ERROR',
    LIFECYCLE_STOPPED = 'LIFECYCLE_STOPPED'
}

function NightShift.Errors.create(code, message, details)
    return {
        code = code or 'NIGHTSHIFT_ERROR',
        message = message or 'NightShift lifecycle failure',
        details = details
    }
end
