ALTER TABLE nightshift_worker_profiles
    ADD COLUMN professionalism TINYINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN discretion TINYINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN reliability TINYINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN completed_bookings INT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN cancelled_bookings INT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN no_show_bookings INT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN last_active_at DATETIME(3) NULL;

ALTER TABLE nightshift_client_profiles
    ADD COLUMN completed_bookings INT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN cancelled_bookings INT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN no_show_bookings INT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN rating DECIMAL(3,2) NOT NULL DEFAULT 0,
    ADD COLUMN tier VARCHAR(32) NOT NULL DEFAULT 'standard',
    ADD COLUMN deposit_risk_score TINYINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN deposit_risk_reason VARCHAR(128) NULL,
    ADD COLUMN last_active_at DATETIME(3) NULL;
