CREATE TABLE IF NOT EXISTS nightshift_agencies (
 id INT UNSIGNED NOT NULL AUTO_INCREMENT,
 agency_key VARCHAR(96) NOT NULL,
 name VARCHAR(120) NOT NULL,
 owner_ref VARCHAR(160) NULL,
 status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
 commission_rate INT UNSIGNED NOT NULL DEFAULT 0,
 members_json LONGTEXT NOT NULL,
 version INT UNSIGNED NOT NULL DEFAULT 1,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (id), UNIQUE KEY uq_nightshift_agency_key (agency_key), KEY idx_nightshift_agency_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
